#!/usr/bin/env sh

# Configure linux environment before running python script

TAP_INTERFACE=tap0
HOST_INTERFACE=eth0

# This configuration allows simulated Linux to connect to the Internet.
# Linux in Renode has the static IP 172.16.0.2/16.

ip tuntap add mode tap ${TAP_INTERFACE} && \
ip addr add "172.16.0.1/16" dev ${TAP_INTERFACE} && \
ip link set up dev ${TAP_INTERFACE} && \
iptables --table nat --append POSTROUTING --out-interface ${HOST_INTERFACE} -j MASQUERADE && \
iptables --append FORWARD --in-interface ${TAP_INTERFACE} -j ACCEPT

exec /run-in-renode.py "$@"
