name: Renode linux tester
inputs:
  shared-dir:
    description: Path to shared directory
    required: true
  renode-run:
    description: Command or a list of commands to run in Renode
    required: true
  devices:
    description: Devices to set up
    required: false
    default: ""
runs:
  using: composite
  steps:
    - id: run
      run: |
        docker run                                              \
        --cap-add=NET_ADMIN                                     \
        --device /dev/net/tun:/dev/net/tun                      \
        -v "$(pwd)"/${{ inputs.shared-dir }}:/mnt/user          \
        ghcr.io/antmicro/renode-linux-runner-action             \
        "${{ inputs.renode-run }}"                              \
        "${{ inputs.devices }}"
      shell: bash
